#############################################################
# Dockerfile to build a sample tool container for BAMStats
#############################################################

# Set the base image to Ubuntu
FROM ubuntu:18.04

# File Author / Maintainer
MAINTAINER Louise Cabansay <lcabansa@ucsc.edu>

# Setup packages
USER root
RUN apt update
RUN apt install bwa
